---
- src: andrewrothstein.git
  version: v3.0.0
- src: andrewrothstein.hub
  version: v1.0.3
- src: andrewrothstein.corkscrew
  version: v1.0.2
- src: andrewrothstein.nettools
  version: v1.0.2
- src: andrewrothstein.docker-binaries
  version: v1.0.2
- src: andrewrothstein.sshd-supervisord
  version: v1.0.4
- src: andrewrothstein.emacs-daemon-supervisord
  version: v1.0.1
