---
- src: andrewrothstein.pkg-upgrade
- src: andrewrothstein.docker-binaries
  version: v1.0.6
- src: andrewrothstein.emacs-daemon-supervisord
  version: v1.0.3
- src: andrewrothstein.git
  version: v3.0.0
- src: andrewrothstein.hub
  version: v1.0.4
- src: andrewrothstein.nettools
  version: v1.0.5
- src: andrewrothstein.sshd-supervisord
  version: v1.0.6
- src: andrewrothstein.kubectl
  version: v1.0.9
- src: andrewrothstein.kubernetes-helm
  version: v1.0.6
- src: andrewrothstein.jq
  version: v1.0.1
