---
- src: andrewrothstein.git
  version: v3.0.0
- src: andrewrothstein.hub
  version: v1.0.3
- src: andrewrothstein.corkscrew
  version: v1.0.2
- src: andrewrothstein.nettools
  version: v1.0.2
- src: andrewrothstein.supervisord
  version: v1.0.5
- src: andrewrothstein.sshd-supervisord
  version: v1.0.1
- src: andrewrothstein.emacs-daemon-supervisord
  version: v1.0.0
- src: spk83.dumb-init
  version: v1.0.0
