---
- src: andrewrothstein.upgrade-pkgs
- src: andrewrothstein.docker-binaries
  version: v1.0.5
- src: andrewrothstein.emacs-daemon-supervisord
  version: v1.0.2
- src: andrewrothstein.git
  version: v3.0.0
- src: andrewrothstein.hub
  version: v1.0.4
- src: andrewrothstein.nettools
  version: v1.0.4
- src: andrewrothstein.sshd-supervisord
  version: v1.0.5
