---
- src: andrewrothstein.pkg-upgrade
- src: andrewrothstein.bash
- src: andrewrothstein.tmux
- src: andrewrothstein.gcc-toolbox
- src: andrewrothstein.git
- src: andrewrothstein.hub
- src: andrewrothstein.nettools
- src: andrewrothstein.jq
- src: andrewrothstein.galaxify
- src: andrewrothstein.vault
- src: andrewrothstein.docker-binaries
- src: andrewrothstein.docker-compose
- src: andrewrothstein.emacs-build
- src: andrewrothstein.emacs-config
- src: andrewrothstein.sshd-supervisord
- src: andrewrothstein.kubectl
- src: andrewrothstein.kubernetes-helm
- src: andrewrothstein.node
- src: andrewrothstein.go-dev
- src: andrewrothstein.scala
- src: andrewrothstein.miniconda
- src: andrewrothstein.dcb
- src: andrewrothstein.packer
- src: andrewrothstein.terraform
- src: andrewrothstein.cfssl
- src: andrewrothstein.pki
- src: andrewrothstein.lastpass-cli

