---
- src: andrewrothstein.pkg-upgrade
- src: andrewrothstein.bash
  version: v1.0.5
- src: andrewrothstein.tmux
  verison: v1.0.0
- src: andrewrothstein.gcc-toolbox
  version: v1.0.6
- src: andrewrothstein.git
  version: v3.0.1
- src: andrewrothstein.hub
  version: v1.0.5
- src: andrewrothstein.nettools
  version: v1.0.5
- src: andrewrothstein.jq
  version: v1.0.2
- src: andrewrothstein.galaxify
  version: v1.0.23
- src: andrewrothstein.vault
  version: v1.2.1
- src: andrewrothstein.docker-binaries
  version: v1.1.0
- src: andrewrothstein.docker-compose
  version: v1.1.0
- src: andrewrothstein.emacs
  version: v2.0.4
- src: andrewrothstein.emacs-config
  version: v1.0.5
- src: andrewrothstein.sshd-supervisord
  version: v1.0.8
- src: andrewrothstein.kubectl
  version: v1.0.17
- src: andrewrothstein.kubernetes-helm
  version: v1.1.1
- src: andrewrothstein.node
  version: v1.2.0
- src: andrewrothstein.go-dev
  version: v2.2.0
- src: andrewrothstein.scala
  version: v2.1.0
- src: andrewrothstein.miniconda
  version: v5.1.0
- src: andrewrothstein.dcb
  version: v1.0.0
- src: andrewrothstein.packer
  version: v2.0.13
- src: andrewrothstein.terraform
  version: v2.2.2
- src: andrewrothstein.cfssl
  version: v2.0.1
- src: andrewrothstein.lastpass-cli
  version: v1.0.0
